function mf_probability_bound = get_mf_probability_bound(mf_probability_bound, varargin)

mf_probability_bound = ...
    @(problem, train_ind_l, observed_labels_l, train_ind_h, observed_labels_h, ...
      test_ind_l, test_ind_h, num_positives_l, num_positives_h, ...
      remain_budget_h) ...
    mf_probability_bound(problem, ...
        train_ind_l, observed_labels_l, train_ind_h, observed_labels_h, ...
        test_ind_l, test_ind_h, num_positives_l, num_positives_h, ...
        remain_budget_h, varargin{:});
