function h_policy = get_h_policy(policy, varargin)

h_policy = @(problem, train_ind_l, observed_labels_l, train_ind_h, ...
    observed_labels_h, unlabeled_ind_l, unlabeled_ind_h) ...
    policy(problem, train_ind_l, observed_labels_l, train_ind_h, ...
        observed_labels_h, unlabeled_ind_l, unlabeled_ind_h, varargin{:});
