function base_policy = get_base_policy(policy, varargin)

base_policy = @(problem, train_ind_l, observed_labels_l, train_ind_h, ...
    observed_labels_h, unlabeled_ind_l, unlabeled_ind_h, choose_h) ...
    policy(problem, train_ind_l, observed_labels_l, train_ind_h, ...
        observed_labels_h, unlabeled_ind_l, unlabeled_ind_h, choose_h, ...
        varargin{:});
