function l_batch_policy = get_l_batch_policy(policy, varargin)

l_batch_policy = @(problem, train_ind_l, observed_labels_l, train_ind_h, ...
    observed_labels_h, unlabeled_ind_l, unlabeled_ind_h, remain_budget_l, ...
    remain_budget_h) ...
    policy(problem, train_ind_l, observed_labels_l, train_ind_h, ...
        observed_labels_h, unlabeled_ind_l, unlabeled_ind_h, remain_budget_l, ...
        remain_budget_h, varargin{:});
