function mf_policy = get_mf_policy(policy, varargin)

mf_policy = @(problem, ...
    train_ind_l, observed_labels_l, train_ind_h, observed_labels_h, ...
    test_ind_l, test_ind_h, return_both) ...
    policy(problem, ...
        train_ind_l, observed_labels_l, train_ind_h, observed_labels_h, ...
        test_ind_l, test_ind_h, return_both, varargin{:});
